name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/GestaoPedidos.Test/GestaoPedidos.Test.csproj

      - name: Sonarqube Begin
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.14.0
          dotnet sonarscanner begin /d:sonar.cs.opencover.reportsPaths=./src/GestaoPedidos.Test/coverage.opencover.xml /d:sonar.cs.vscoveragexml.reportsPaths=./src/GestaoPedidos.Test/coverage.opencover.xml /o:fiap /k:usuario /d:sonar.login=sqa_b632c864822aeae6d1e1c5f000363596eeb65460 /d:sonar.verbose=true /d:sonar.dotnet.excludeTestProjects=true /d:sonar.host.url=http://54.161.116.110:9000

      - name: Build
        run: dotnet build --configuration Release --output ./artifacts/

      - name: Build Test Project
        run: dotnet build src/GestaoPedidos.Test --configuration Release
      
      - name: Run Tests with Coverage
        run: dotnet test --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Configuration=Release

      # - name: Dotnet Build
      #   run: |
      #     dotnet build .

      # - name: Build
      #   run: dotnet build --configuration Release --output ./artifacts/

      # - name: Restore Dependencies
      #   run: dotnet restore src/GestaoPedidos.Test/GestaoPedidos.Test.csproj

      # - name: Build Test Project
      #   run: dotnet build src/GestaoPedidos.Test --configuration Release

      # - name: Generate Test Coverage
      #   run: |
      #     dotnet test --no-build --no-restore --filter FullyQualifiedName~GestaoPedidos.Test.* /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Configuration=Release

      # - name: Generate Test Coverage
      #   run: |
      #     dotnet test --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: List
        run:
          ls -la ./src/GestaoPedidos.Test/

      - name: Sonarqube End
        run: |
          dotnet sonarscanner end /d:sonar.login=sqa_b632c864822aeae6d1e1c5f000363596eeb65460

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Install dotnet Lambda
        run: |
          dotnet tool install --global Amazon.Lambda.Tools

      - name: Deploy lambda
        run: |